liquibase:
  changeLogFile: src/main/resources/db/changelog/db.changelog-master.yaml

openapi:
  info:
    title: Spring-Boot-Base-API
    description: A base on which to develop an API using Spring
    version: 1.0.0