name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  ci-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # - name: Build image
      #   run: docker build -f Dockerfile.build -t spring-boot-base-api .

      - name: Run tests
        run: make clean build
